"""make nic optional

Revision ID: 366d737c23c0
Revises: 89aac3aa8c9f
Create Date: 2026-03-23 06:43:45.277932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366d737c23c0'
down_revision: Union[str, Sequence[str], None] = '89aac3aa8c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workers', 'nic_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workers', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workers', 'primary_skill',
               existing_type=postgresql.ENUM('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'MASONRY', 'PAINTING', 'GARDENING', 'CLEANING', 'DRIVING', 'GENERAL_LABOR', 'OTHER', name='skill_category'),
               nullable=True)
    op.drop_constraint(op.f('workers_nic_number_key'), 'workers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('workers_nic_number_key'), 'workers', ['nic_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('workers', 'primary_skill',
               existing_type=postgresql.ENUM('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'MASONRY', 'PAINTING', 'GARDENING', 'CLEANING', 'DRIVING', 'GENERAL_LABOR', 'OTHER', name='skill_category'),
               nullable=False)
    op.alter_column('workers', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workers', 'nic_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('provider_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
